=== ctipper/perspective/xml/dtd/perspective-schema.dtd
<!-- ...................................................................... -->
<!-- perspective XML DTD V2.6.0 ........................................... -->
<!-- File perspective-schema.dtd .......................................... -->

<!-- Copyright Â© 2003, 2005, 2007, 2016, 2017, 2018 Christopher Tipper
A DTD for a reduced markup language, and simple blog

  Namespace "http://www.e-conomist.me.uk/xml/dtd/perspective-schema.dtd"
  PUBLIC    "-//CTIPPER//DTD perspective XML V2.1//EN" 

-->

<!-- ...................................................................... -->

<!-- %inline;
An inline element. 
-->

<!ENTITY % inline "#PCDATA | i | b | u | tt | sup | sub | sq | q | apos">

<!-- %itags;
itags are inline elements that are used in a different context. 
-->

<!ENTITY % itags "cite | a">

<!-- ...................................................................... -->

<!-- document is the top-level element  -->

<!ELEMENT document (info, body , bibliography?)>

<!-- info holds meta-information -->

<!ELEMENT info (title, subtitle, author, date?, copyright?, keywords?, revhistory?, introduction?)>

<!-- body holds the content  -->

<!ELEMENT body          (blog | section | p+ | enumerate | itemize | sub-heading | center | blockquote | table | hr | a | img | byline | pre | epigraph)*>

<!-- section separates content -->

<!ELEMENT section       (title, (p+ | enumerate | itemize | sub-heading | center | blockquote | table | hr | a | img | byline | pre | epigraph)*)>
<!ATTLIST section 
          id            CDATA                       #IMPLIED
>

<!-- blog constructs -->

<!ELEMENT blog         (bloginfo, (p+ | enumerate | itemize | sub-heading | center | blockquote | table | hr | a | img | byline | pre | epigraph)*)> 
<!ATTLIST blog 
          id            CDATA                       #REQUIRED
>

<!ELEMENT bloginfo      (title, date, keywords?)>

<!-- meta information is contained in the following tags -->

<!ELEMENT title         (%inline;)*>

<!ELEMENT subtitle      (%inline;)*>

<!ELEMENT author        (#PCDATA)>

<!ELEMENT date          (#PCDATA)>

<!ELEMENT copyright     (owner, year)>

<!ELEMENT owner         (#PCDATA)>

<!ELEMENT year          (#PCDATA)>

<!ELEMENT keywords      (#PCDATA)>

<!ELEMENT revhistory    (revision)+>

<!ELEMENT revision      (revnumber, revdate, revremark)>

<!ELEMENT revdate       (#PCDATA)>

<!ELEMENT revnumber     (#PCDATA)>

<!ELEMENT revremark     (%inline; | a)*>

<!ELEMENT introduction  (p)+>

<!-- ...................................................................... -->

<!-- inline element declarations -->

<!ELEMENT sq            (%inline; | %itags;)*>

<!ELEMENT q             (%inline; | %itags;)*>

<!ELEMENT sup           (#PCDATA)>

<!ELEMENT sub           (#PCDATA)>

<!ELEMENT cite          (#PCDATA)>

<!ELEMENT b             (%inline; | %itags;)*>

<!ELEMENT u             (%inline; | %itags;)*>

<!ELEMENT i             (%inline; | %itags;)*>

<!ELEMENT tt            (%inline; | %itags;)*>

<!ELEMENT footnote      (%inline; | %itags; | p)*>

<!ELEMENT byline        (%inline; | %itags;)*>

<!ELEMENT a             (%inline;)*>
<!ATTLIST a 
          href          CDATA           "#" 
          name          CDATA           #IMPLIED
          title         CDATA           #IMPLIED
          type          CDATA           #IMPLIED
          property      CDATA           #IMPLIED
>
          
<!ELEMENT hr            EMPTY>

<!ELEMENT stop          EMPTY>

<!ELEMENT apos          EMPTY>

<!ELEMENT annotation    (title, p+)>

<!-- ...................................................................... -->

<!-- block element declarations -->

<!ELEMENT p             (%inline; | %itags; | img | footnote | annotation | stop)*>
<!ATTLIST p 
          align         (left | right | center)     #IMPLIED
          class         CDATA                       #IMPLIED
>
          
<!ELEMENT pre           (%inline; | %itags; | footnote)*>

<!ELEMENT center        (%inline; | %itags; | img | footnote | stop)*>
<!ATTLIST center 
          class         CDATA                       #IMPLIED
>
          
<!ELEMENT blockquote    (p)+>

<!ELEMENT epigraph      (p)+>

<!ELEMENT sub-heading   (%inline; | %itags;)*>

<!ELEMENT enumerate     (item)+>
<!ATTLIST enumerate
          style         (1 | a | A | i | I)         #IMPLIED
>

<!ELEMENT itemize       (item)+>

<!ELEMENT item          (p)+>

<!-- ...................................................................... -->

<!-- image inclusion 
     * dimensions are pixels, with implied resolution of 96dpi
     * src attribute represents image name _without_ file extension
     * alt is a required attribute
     * align default is 'center'
     * space attribute is padding in pixels around image
     * pdfres attribute represents pdf resolution in dpi
     * float set to 'yes' for floating image in pdf output
-->

<!ELEMENT img (caption)*>
<!ATTLIST img 
          src           CDATA                           #REQUIRED
          width         CDATA                           #REQUIRED
          height        CDATA                           #REQUIRED
          alt           CDATA                           #REQUIRED
          align         (left | right | center)         #IMPLIED
          space         CDATA                           #IMPLIED
          border        CDATA                           #IMPLIED
          format        (jpg | gif | png | svg | pdf)   #REQUIRED
          pdfres        CDATA                           #IMPLIED
          float         CDATA                           #IMPLIED
>
          
<!ELEMENT caption       (%inline; | %itags;)*>
<!ATTLIST caption 
          figure        (yes | no)                      #IMPLIED
>
          
<!-- ...................................................................... -->

<!-- reduced bibliography markup 
We do not need the more elaborate schemes elsewhere 
as we are only dealing with books and journals.
-->

<!ELEMENT bibliography (bibitem)*>

<!ELEMENT bibitem       (author | editor | title | month | year | journal | publisher | edition | note)+>
<!ATTLIST bibitem 
          type          (article | book)                #REQUIRED
          label         CDATA                           #REQUIRED
>

<!ELEMENT editor        (#PCDATA)>

<!ELEMENT journal       (#PCDATA | a)*>

<!ELEMENT publisher     (#PCDATA)>

<!ELEMENT month         (#PCDATA)>

<!ELEMENT edition       (#PCDATA)>

<!ELEMENT note          (%inline; | %itags;)*>

<!-- ...................................................................... -->

<!-- table markup
Allows simplified tables compatible with HTML table model
-->

<!ELEMENT table         (label?, tgroup+)>
<!ATTLIST table 
          align         (left | right | center)     #IMPLIED
>

<!ELEMENT label         (%inline; | %itags;)*>
<!ATTLIST label
          number        (yes | no)                  #IMPLIED
>

<!ELEMENT tgroup        (columns+, thead?, tfoot?, tbody)>
<!ATTLIST tgroup 
          cols          CDATA                       #REQUIRED
>
          
<!ELEMENT columns       EMPTY>
<!ATTLIST columns 
          number        CDATA                       #REQUIRED
          width         CDATA                       #IMPLIED
          align         (left | right | center)     #IMPLIED
>
          
<!ELEMENT thead         (row)*>
          
<!ELEMENT tfoot         (row)*>

<!ELEMENT tbody         (row)*>

<!ELEMENT row           (column)*>
<!ATTLIST row 
          valign        (top | middle | bottom)     #IMPLIED
>
          
<!ELEMENT column        (%inline; | %itags; | p | footnote | annotation)*>
<!ATTLIST column 
          align         (left | center | right)     #IMPLIED
          span          CDATA                       #IMPLIED
          class         CDATA                       #IMPLIED
>
          
<!-- ...................................................................... -->

<!-- ISO character entities -->

<!ENTITY % ISOlat1.module "INCLUDE">
<![%ISOlat1.module;[
<!ENTITY % ISOlat1 PUBLIC
"ISO 8879:1986//ENTITIES Added Latin 1//EN//XML"
"entities/iso-lat1.ent">
<!--end of ISOlat1.module-->]]>

<!ENTITY % ISOnum.module "INCLUDE">
<![%ISOnum.module;[
<!ENTITY % ISOnum PUBLIC
"ISO 8879:1986//ENTITIES Numeric and Special Graphic//EN//XML"
"entities/iso-num.ent">
<!--end of ISOnum.module-->]]>

<!ENTITY % ISOpub.module "INCLUDE">
<![%ISOpub.module;[
<!ENTITY % ISOpub PUBLIC
"ISO 8879:1986//ENTITIES Publishing//EN//XML"
"entities/iso-pub.ent">
<!--end of ISOpub.module-->]]>

<!ENTITY % ISOmisc.module "INCLUDE">
<![%ISOmisc.module;[
<!ENTITY % ISOmisc PUBLIC
"ISO 8879:1986//ENTITIES Miscellaneous//EN//XML"
"entities/iso-misc.ent">
<!--end of ISOmisc.module-->]]>

<![ %ISOlat1.module; [
%ISOlat1;
]]>

<![ %ISOnum.module; [
%ISOnum;
]]>

<![ %ISOpub.module; [
%ISOpub;
]]>

<![ %ISOmisc.module; [
%ISOmisc;
]]> 

<!-- ..................................................................... -->
<!-- End of perspective-schema dtd -->

=== ctipper/perspective/xml/tropical.xml
<?xml version="1.0"?>
<!DOCTYPE document PUBLIC "-//CTIPPER//DTD perspective XML V2.1//EN" "dtd/perspective-schema.dtd">
<document>
   <info>
      <title>Table example</title>
      <subtitle>An example table used for testing</subtitle>
      <author>Christopher Tipper</author>
      <date>June 2004</date>
      <copyright>
         <owner>Christopher Tipper</owner>
         <year>2004</year>
      </copyright>
   </info>
   <body>
      <p>We thrive in information-thick worlds because of our marvelous and everyday 
      capacity to select, edit, single out, structure, highlight, group, pair, merge, 
      harmonize, synthesize, focus, organize, condense, reduce, boil down, choose, 
      categorize, catalog, classify, list, abstract, scan, look into, idealize,<footnote>Ideal&mdash;see 
      <a href="http://classics.mit.edu/Plato/">Plato</a></footnote> isolate, 
      discriminate, distinguish, screen, pigeonhole, pick over, sort, integrate, blend, 
      inspect, filter, lump, skip, smooth, chunk, average, approximate, cluster, aggregate, 
      outline, summarize, itemize, review, dip into, flip through, browse, glance 
      into, leaf through, skim, refine, enumerate, glean, synopsize, winnow the wheat 
      from the chaff and separate the sheep from the goats. </p>
      <table align="center">
         <label number="yes">Scope and incidence of Tropical Diseases, 1990</label>
         <tgroup cols="4">
            <columns number="1" width="195" align="left"/>
            <columns number="2" width="115" align="right"/>
            <columns number="3" width="137" align="right"/>
            <columns number="4" width="115" align="right"/>
            <thead>
               <row>
                  <column>Disease</column>
                  <column align="center">Countries</column>
                  <column align="center">Number</column>
                  <column align="center">Number at</column>
               </row>
               <row>
                  <column>&nbsp;</column>
                  <column align="center">Afflicted</column>
                  <column align="center">Infected<footnote>&rsquo;000</footnote></column>
                  <column align="center">risk<footnote>&rsquo;000,000</footnote></column>
               </row>
            </thead>
            <tfoot>
               <row>
                  <column span="4">SOURCE: World Health Organisation (WHO), Special Program, for Research and Training in Tropical Diseases, 1990.</column>
               </row>
            </tfoot>
            <tbody>
               <row>
                  <column>Malaria</column>
                  <column>103</column>
                  <column>270,000</column>
                  <column>2,100</column>
               </row>
               <row>
                  <column>Schistomiasis</column>
                  <column>76</column>
                  <column>200,000</column>
                  <column>600</column>
               </row>
               <row>
                  <column>Lymphatic filiarisis</column>
                  <column>76</column>
                  <column>90,000</column>
                  <column>900</column>
               </row>
               <row>
                  <column>River blindness</column>
                  <column>34</column>
                  <column>17,000</column>
                  <column>90</column>
               </row>
               <row>
                  <column>Chagas&rsquo; disease</column>
                  <column>21</column>
                  <column>16-18,000</column>
                  <column>90</column>
               </row>
               <row>
                  <column>Leishmaniasis</column>
                  <column>80</column>
                  <column>12,000</column>
                  <column>350</column>
               </row>
               <row>
                  <column>Leprosy</column>
                  <column>121</column>
                  <column>10-12,000</column>
                  <column>1,600</column>
               </row>
               <row>
                  <column>African sleeping sickness</column>
                  <column>36</column>
                  <column>25</column>
                  <column>50</column>
               </row>
            </tbody>
         </tgroup>
      </table>
   </body>
</document>

=== ctipper/perspective/xml/perspective-readme.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE document PUBLIC "-//CTIPPER//DTD perspective XML V2.1//EN" "dtd/perspective-schema.dtd">
<document>
   <info>
      <title>Perspective XSLT stylesheets</title>
      <subtitle>A solution for publishing to print and web</subtitle>
      <author>Christopher Tipper</author>
      <date>Saturday, 12th March 2005</date>
      <copyright>
         <owner>Christopher Tipper</owner>
         <year>2005</year>
      </copyright>
      <keywords>stylesheets, xsl, XSLT, html, docbook, tcl/tk, apache FOP</keywords>
   </info>
   <body>
      <img src="tx-1" format="jpg" width="466" height="206" alt="A Tcl GUI to produce the transformation to HTML and print" align="center" space="10" border="0" pdfres="200">
         <caption>Tx.tcl greatly expedites the transformation of the output to XHTML and 
      Print.</caption></img>
      <p><q>Perspective</q> is a macro and stylesheet distribution that allows you to 
      publish structured documents to web and print. The stylesheets in this distribution
      allow the creation and transformation of XML to HTML, PDF (using Formatting-Objects via XSLT) and 
      DocBook, a widely used XML standard. This page and the accompanying PDF were 
      produced using this software.</p>
      <p>The importance of semantic markup is that you will have a clear
      separation between style and content, the same content being used to generate
      layouts in many media. Other solutions based on Wiki style markup of plain text
      don<apos/>t properly take into account document meta information, and they
      certainly don<apos/>t handle bibliographic data. This package provides that as
      well as generating compact and semantically meaningful XML that can be
      transformed to any other schema. This package produces XML to the
      <a href="http://docbook.sourceforge.net/">Docbook</a> schema, for example. DocBook
      may then be used for transforming to present and future formats such as the <a
      href="http://www.openebook.org/">epub</a> format (using the most recent versions
      of the <a href="http://sourceforge.net/projects/docbook/">DocBook XSL
      stylesheets</a>) used in the <a href="http://en.wikipedia.org/wiki/Sony_Reader">Sony Reader</a> and <a
      href="http://www.adobe.com/products/digitaleditions/">Adobe Digital
      Editions</a>.</p>
      <p>The perspective-schema DTD allows the creation of articles with hyperlinks, 
      footnote entries, itemised lists, tables, image inclusions and citations, as 
      well as certain inline elements such as superscripts, bold, underline and 
      italic. It also handles proper quotation marks and a useful subset of foreign 
      characters and currency symbols. The XSLT stylesheet will insert a drop cap at 
      the start of the text body, process footnotes to provide forward and backward 
      links, and create author initials in bibliographic entries. </p>
      <p>Perspective provides a DTD for a reduced markup language, </p>
      <pre>Namespace
      <a href="http://www.e-conomist.me.uk/xml/dtd/perspective-schema.dtd">http://www.e-conomist.me.uk/xml/dtd/perspective-schema.dtd</a>
      PUBLIC    "-//CTIPPER//DTD perspective XML V2.1//EN"</pre>
      <p>A Workflow can be defined as follows:</p>
      <enumerate>
         <item><p>Create perspective DTD-based XML document based documents from the
         samples in xml folder.</p></item>
         <item><p>Output may be produced by using the supplied Tcl/Tk scripts which use:</p></item>
         <item><p>Output HTML using <tt>stylesheet/html-dbk-perspective.xsl</tt></p></item>
         <item><p>Output Docbook XML using <tt>stylesheet/dbk-perspective.xsl</tt></p></item>
         <item><p>Output alternate HTML using <tt>stylesheet/html-perspective.xsl</tt></p></item>
         <item><p>Output PDF by transforming to formatting-objects with
         <tt>stylesheet/fo-perspective.xsl</tt> and then using the fop renderer</p></item>
      </enumerate>
      <p class="lead">Notes:</p>
      <p>The supplied Tcl scripts uses xsltproc and trang validator. You may use GNOME libxml to process 
      the pages. See your operating system documentation. Libxml2 is bundled by default  
      on macOS.</p>
      <p>To produce PDF you will need a FO renderer, such as Apache FOP <a href="https://xmlgraphics.apache.org/fop/">https://xmlgraphics.apache.org/fop/</a>
      Installation is somewhat involved see documentation particularly if you need
      non-standard fonts and hyphenation.</p>
      <p>Typical command-lines as follows:</p>
      <sub-heading>XHTML</sub-heading>
      <pre>xsltproc.exe --stringparam file-name e-template 
             --stringparam path-name "" --output ..\e-template.html 
..\stylesheets\html-perspective.xsl e-template.xml</pre>
      <sub-heading>PDF</sub-heading>
      <pre>xsltproc.exe --stringparam file-name e-template 
             --stringparam path-name ../ --stringparam fo-processor xep 
--output e-template.fo ..\stylesheets\fo-perspective.xsl e-template.xml</pre>
      <p>then</p>
      <pre>c:\xep\xep.bat e-template.fo</pre>
      <p>The variable <tt>path-name</tt> refers to the path to images/ from the output 
      directory: uses the Unix path syntax i.e. forward slash.</p>
      <sub-heading>Docbook</sub-heading>
      <pre>xsltproc.exe --output ..\docbook\e-template.xml
..\stylesheets\dbk-perspective.xsl e-template.xml</pre>
      <sub-heading>LICENSE&mdash;see LICENSE.txt</sub-heading>
      <p>The license for this product (<q>LICENSE.txt</q>) is fairly standard.
      Modification of the software is at the user<apos/>s own risk, all derivative
      products must give proper attribution. <stop /></p>
   </body>
</document>

=== ctipper/perspective/xml/perspective.xml
<?xml version="1.0"?>
<!DOCTYPE document PUBLIC "-//CTIPPER//DTD perspective XML V2.1//EN" "dtd/perspective-schema.dtd">
<document>
   <info>
      <title>This is the author<apos/>s <q>Title</q></title>
      <subtitle>This is the article<apos/>s subtitle</subtitle>
      <author>Christopher Tipper</author>
      <date>Saturday, 12th March 2005</date>
      <copyright>
         <owner>Christopher Tipper</owner>
         <year>2005</year>
      </copyright>
      <keywords>Wd2XML, perspective DTD, more keywords</keywords>
      <introduction>
         <p>This is a demonstration of the ::perspective stylesheets. It is not a 
         comprehensive collection at present, merely implementing those markup 
         elements that are needed to support general article semantics, such as 
         footnotes, bibliography support, lists of various types, tables and image 
         inclusion.</p>
         <p>New elements will be added as and when required.</p>
      </introduction>
   </info>
   <body>
      <img src="dijon" format="jpg" width="233" height="317" alt="Hospices de Beaune" 
           align="right" space="10" border="0" pdfres="200"><caption figure="yes">The H&ocirc;spices de 
      Beaune Hospital <q>H&ocirc;tel Dieu</q> was built in 1443 by Nicola Rodin, Chancellor
      of Philippe le-Bon, Duke of Burgundy. In the wake of the Hundred Years<apos/> War,
      Beaune was suffering from famine. Today it runs 61 hectares of vines and each year since
      1859 it has organised the most famous wine auction in the world.</caption></img>
      <p>Article text goes here. And this has a footnote.<footnote><p>This is an 
      explanatory endnote.</p></footnote> Some <sq>single quotes</sq> and <q>double-quotes</q> and foreign <u><i><b>characters</b></i></u> 
      &mdash;&dollar;&pound;&yen;&euro;&cent;&copy;&deg;&plusmn;&half;&szlig;&uuml;&auml;&aacute;&agrave;&eacute;&egrave;. And there's more: 
      &ecirc;&ouml;&ocirc;&ccedil;&oslash;.</p>
      <sub-heading>sub-heading</sub-heading>
      <p>Quoted text</p>
      <blockquote>
         <p>We thrive in information-thick worlds because of our marvelous and 
         everyday capacity to select, edit, single out, structure, highlight, group, 
         pair, merge, harmonize, synthesize, focus, organize, condense, reduce, boil 
         down, choose, categorize, catalog, classify, list, abstract, scan, look into, 
         idealize, isolate, discriminate, distinguish, screen, pigeonhole, pick over, 
         sort, integrate, blend, inspect, filter, lump, skip, smooth, chunk, average, 
         approximate, cluster, aggregate, outline, summarize, itemize, review, dip 
         into, flip through, browse, glance into, leaf through, skim, refine, 
         enumerate, glean, synopsize, winnow the wheat from the chaff and separate the 
         sheep from the goats. </p>
      </blockquote>
      <a name="Thuc01"></a><p class="text-muted"><sup>6.8</sup> At the beginning of  
      spring 415 BC the Athenian delegation returned from Sicily. They brought with 
      them the Egestaeans and sixty talents of uncoined silver, a months pay for 
      sixty triremes and their supplies.</p>
      <p class="text-muted">The Athenians held an assembly and heard the Egestaeans 
      and their own envoys. It was reported that there were large quantities of 
      money in the treasury and the temples, and they voted to send sixty ships 
      under the command of three generals, Alcibiades, Nicias and Lamachus. They 
      were appointed with full powers and given orders to help the Egestaeans 
      against the Selinuntines, to restore Leontini subsequent to victory and act 
      in the best interests of Athens with regard to further action in Sicily. 
      <cite>Thucydides</cite></p>
      <p>In practice, the distinction between noosphere and ergosphere is not 
      important for the purposes of this paper. It is dubious whether the 
      <sq>noosphere</sq> in the pure sense Fare insists on can be said to exist in 
      any meaningful way; one would almost have to be a Platonist philosopher to 
      believe in it. And the distinction between noosphere and ergosphere is only 
      of <i>practical </i>importance if one wishes to assert that ideas (the 
      elements of the noosphere) cannot be owned, but their instantiations as 
      projects can.</p>
      <p class="font-italic">To avoid confusion, however, it is important to 
      note that neither the noosphere nor the ergosphere is the same as the 
      totality of virtual locations in electronic media that is sometimes called 
      <sq>cyberspace</sq>. Property there is regulated by completely different 
      rules that are closer to those of the material substratum&mdash;essentially, 
      he who owns the media and machines on which a part of <sq>cyberspace</sq> is 
      hosted owns that piece of cyberspace as a result.</p>
      <p>More article text goes here with a citation <cite>Chaitin</cite>.</p>
      <p>An we now add a simple enumeration:</p>
      <enumerate>
         <item><p>This is the <sq>first</sq> item. </p></item>
         <item><p>This is the <sq>second</sq> item. </p></item>
         <item><p>This is the <sq>third</sq> item.</p></item>
      </enumerate>
      <p>Article text goes here with another citation <cite>Mill</cite>.</p>
      <p>An we now add a bulletted list:</p>
      <itemize>
         <item><p>Item One.</p></item>
         <item><p>Item Two.</p></item>
         <item><p>Item Three.</p></item>
      </itemize>
      <p>And now we conclude the article with a stop character. <stop /></p>
   </body>
   <bibliography>
      <bibitem type="article" label="Chaitin">
         <author>Gregory Chaitin</author>
         <month>May</month>
         <year>1975</year>
         <title>Randomness and Mathematical Proof</title>
         <journal>Scientific American 232, No 5</journal>
         <note>pp. 47-52</note>
      </bibitem>
      <bibitem type="book" label="Mill">
         <author>John Stuart Mill</author> 
         <year>1863</year> 
         <title>Utilitarianism</title>
         <publisher>London: Parker, Son, and Bourn</publisher>
         <edition>1st</edition>
         <note><i>vivus</i> 1806-1873</note>
      </bibitem>
      <bibitem type="book" label="Thucydides"> 
         <author>Thucydides</author>
         <editor>Rex Warner</editor>
         <title>The Peloponnesian War</title>
         <year>1972</year> 
         <publisher>Harmondsworth, Middlesex: Penguin Books</publisher>
         <note><a href="#Thuc01">Back</a></note>
      </bibitem>
   </bibliography>
</document>
